name: ml_dsa_example
description: "Demonstrates how to use ml_dsa."
version: 0.0.1+1
publish_to: 'none'

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  ml_dsa:
    path: ../
  cupertino_icons: ^1.0.8
  hex: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  benchmark_harness: ">=2.0.0 <3.0.0"

flutter:
  uses-material-design: true
