name: ml_dsa
description: "Module-Lattice-Based Digital Signature Standard"
version: 0.0.1+1
homepage: https://github.com/jasoncolburne/ml-dsa-flutter
publish_to: none

environment:
  sdk: ^3.6.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  keccak:
    path: plugins/keccak

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
