name: Flutter Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
    - name: Pub Get
      run: |
        cd example
        flutter pub get
    - name: Test
      run: |
        cd example
        CMAKE_CXX_COMPILER=cc flutter test -d linux integration_test/*
